#!/usr/bin/perl
###############################################################################
use diagnostics;
use Net::SNMP;
use strict;
use warnings;
###############################################################################
my $VoltageOID = ".1.3.6.1.4.1.14988.1.1.3.8.0";
my $SNMPCommunity = "public";
my $SNMPPort = "161";

###############################################################################
## Determine Hostname
my $Host = undef;
$0 =~ /mikrotikvoltage_(.+)*$/;
unless ($Host = $1) {
  exit 2;
}

###############################################################################
## Initiate SNMP Session
my ($Session, $Error) = Net::SNMP->session (-hostname  => $Host,
                                            -community => $SNMPCommunity,
                                            -port      => $SNMPPort,
                                            -timeout   => 60,
                                            -retries   => 5,
                                            -version   => 1);
if (!defined($Session)) {
  die "Croaking: $Error";
}

###############################################################################
## Configuration
if ($ARGV[0] && $ARGV[0] eq "config") {
  print "host_name " . $Host . "\n";
  print "graph_args -l 0 --vertical-label volts --lower-limit 8 --upper-limit 38\n";
  print "graph_title Mikrotik Voltage\n";
  print "graph_category system\n";
  print "graph_info This graph shows the router's voltage.\n";
  print "graph_order Total\n";
  print "graph_vlabel Volts\n";
  print "graph_scale no\n";
  print "Voltage.label Voltage\n";
  print "Voltage.warning 12:\n";
  print "Voltage.critical 10:\n";
  $Session->close;
  exit;
}

###############################################################################
## Execution
if (my $Result = $Session->get_request(-varbindlist => [$VoltageOID])) {
  print "Voltage.value " . $Result->{$VoltageOID}/10.0 . "\n";
  $Session->close;
  exit;
}
