#!/usr/bin/perl
###############################################################################
use diagnostics;
use Net::SNMP;
use strict;
use warnings;
###############################################################################
my $TemperatureOID = ".1.3.6.1.4.1.14988.1.1.3.10.0";
my $SNMPCommunity = "public";
my $SNMPPort = "161";

###############################################################################
## Determine Hostname
my $Host = undef;
$0 =~ /mikrotiktemperature_(.+)*$/;
unless ($Host = $1) {
  exit 2;
}

###############################################################################
## Initiate SNMP Session
my ($Session, $Error) = Net::SNMP->session (-hostname  => $Host,
                                            -community => $SNMPCommunity,
                                            -port      => $SNMPPort,
                                            -timeout   => 60,
                                            -retries   => 5,
                                            -version   => 1);
if (!defined($Session)) {
  die "Croaking: $Error";
}

###############################################################################
## Configuration
if ($ARGV[0] && $ARGV[0] eq "config") {
  print "host_name " . $Host . "\n";
  print "graph_args -l 0 -r --vertical-label percent --lower-limit 0 --upper-limit 100\n";
  print "graph_title Mikrotik Temperature\n";
  print "graph_category system\n";
  print "graph_info This graph shows the router's internal temperature.\n";
  print "graph_order Total\n";
  print "graph_vlabel %\n";
  print "graph_scale no\n";
  print "Temperature.label Temperature (degress C)\n";
  print "Temperature.draw AREA\n";
  print "Temperature.warning 60\n";
  print "Temperature.critical 90\n";
  $Session->close;
  exit;
}

###############################################################################
## Execution
if (my $Result = $Session->get_request(-varbindlist => [$TemperatureOID])) {
  print "Temperature.value " . $Result->{$TemperatureOID}/10.0 . "\n";
  $Session->close;
  exit;
}
